kind: pipeline
type: docker
name: pipe1
steps:
- name: build
  image: alpine:latest
  commands:
  - echo "Frontend building"
- name: backend
  image: alpine:latest
  commands:
  - echo "Backend building"
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: webhook_url
    channel:
      from_secret: slack_channel
    template: >
      {{#success build.status}}
        Successful [{{build.event}}], <{{build.link}}|#{{build.number}}>. used time {{since build.started}}
      {{else}}
        Failed [{{build.event}}], <{{build.link}}|#{{build.number}}>
      {{/success}}