kind: pipeline
type: docker
name: pipe1
steps:
- name: lint
  image: harryuan65/rubocop-docker
  commands:
  - rubocop -v
  - rubocop
- name: tests
  image: ruby:2.7.2-alpine
  commands:
  - apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
  - bundle install
  - echo "Running Tests..."
  - bin/rspec -v
  - bin/rspec
- name: notify
  image: plugins/slack
  when:
    status: [ success, failure ]
  settings:
    webhook:
      from_secret: webhook_url
    channel:
      from_secret: slack_channel
    template: >
      {{#success build.status}}
        Successful [{{build.event}}], <{{build.link}}|#{{build.number}}>. used time {{since build.started}}
      {{else}}
        Failed [{{build.event}}], <{{build.link}}|#{{build.number}}>
      {{/success}}